// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference path=".nuxt-node/nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path=".nuxt-node/components.d.ts" />
/// <reference path=".nuxt-node/auto-imports.d.ts" />
export {}
