nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  rollup-plugin-esbuild@*:
    peerDependencies:
      rollup: "*"
  '@nuxtjs/eslint-config-typescript@*':
    peerDependencies:
      eslint: "*"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
