name: "\U0001F41E Bug report (Nuxt Bridge)"
description: Create a report to help us improve Nuxt Bridge
labels: [bug, bridge]
body:
  - type: markdown
    attributes:
      value: |
        Please carefully read the contribution docs before creating a bug report
        👉 https://v3.nuxtjs.org/community/reporting-bugs

        Please use the code sandbox template below to create a minimal reproduction
        👉 https://codesandbox.io/s/github/nuxt/starter/tree/bridge-codesandbox
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: You can use `npx nuxi info` to fill this section
      placeholder: Environment
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into. A [minimal reproduction](https://v3.nuxtjs.org/community/reporting-bugs#create-a-minimal-reproduction) is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided after we might close it.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here`
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.

        1. Run `vite` or `vite build` with the `--debug` flag.
        2. Provide the error log here.
      render: shell
  # - type: checkboxes
  #   id: checkboxes
  #   attributes:
  #     label: Validations
  #     description: Before submitting the issue, please make sure you do the following
  #     options:
  #       - label: Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
  #         required: true
  #       - label: Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
  #         required: true
  #       - label: Read the [docs](https://vitejs.dev/guide).
  #         required: true
  #       - label: Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
  #         required: true
  #       - label: Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
  #         required: true
  #       - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
  #         required: true
  #       - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
  #         required: true
