
// Delcarations auto generated by `nuxt prepare` at 2021-07-26T12:10:22.380Z
// Please do not manually modify this file

/// <reference types="@nuxt/kit" />
/// <reference types="@nuxt/nitro" />
/// <reference types="@nuxt/pages" />
/// <reference types="@nuxt/meta" />
/// <reference types="@nuxt/component-discovery" />
