// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxt/kit" />
/// <reference types="@nuxt/app" />
/// <reference types="@nuxt/nitro" />
/// <reference types="@nuxt/global-imports" />
/// <reference types="@nuxt/pages" />
/// <reference types="@nuxt/meta" />
/// <reference types="@nuxt/component-discovery" />
/// <reference path=".nuxt/global-imports.d.ts" />
/// <reference path=".nuxt/components.d.ts" />
export {}
