name: Docs

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main

jobs:
  lint-docs:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint (docs)
        run: pnpm lint:docs
